"""MMEX stored values (desktop Model_Checking / TagLink)."""

NOT_SET = -1

TRANS_WITHDRAWAL = "Withdrawal"
TRANS_DEPOSIT = "Deposit"
TRANS_TRANSFER = "Transfer"
TRANS_CODES = (TRANS_WITHDRAWAL, TRANS_DEPOSIT, TRANS_TRANSFER)

STATUS_NONE = ""
STATUS_RECONCILED = "R"
STATUS_VOID = "V"
STATUS_FOLLOWUP = "F"
STATUS_DUPLICATE = "D"
STATUS_CYCLE = (
    STATUS_NONE,
    STATUS_RECONCILED,
    STATUS_VOID,
    STATUS_FOLLOWUP,
    STATUS_DUPLICATE,
)

REF_TRANSACTION = "Transaction"
REF_TRANSACTION_SPLIT = "TransactionSplit"

COLOR_NONE = -1
COLOR_IDS = (-1, 0, 1, 2, 3, 4, 5, 6, 7)
COLOR_MAX = 7
